Repository G-Epitech/MAYBDF-ArcadeShared, pull requests merged in 2024-03, with the labels that each got.

#2 feat: add project template
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/new-feature.yml
  .github/ISSUE_TEMPLATE/tests.yml
  .github/pull_request_template.md
  IDisplay.hpp
  IGame.hpp
Labels: configuration

#6 Create games interfaces
  .gitignore
  IDisplay.hpp
  IGame.hpp
  games/entity/IDisplayableEntity.hpp
  games/entity/IEntity.hpp
  games/game/IGame.hpp
  games/types/GameManifest.hpp
  games/types/KeyData.hpp
  games/types/SoundProps.hpp
  games/types/TextureProps.hpp
  types/UUId.hpp
  types/Vector.hpp
  types/types.hpp
Labels: enhancement

#9 docs: add README.md
  README.md
Labels: documentation

#12 Add graphics part and refactor games part
  games/IEntity.hpp
  games/IGame.hpp
  games/components/ICollidableComponent.hpp
  games/components/IComponent.hpp
  games/components/IDisplayableComponent.hpp
  games/components/IKeyboardComponent.hpp
  games/components/IPositionComponent.hpp
  games/components/ISoundComponent.hpp
  games/entity/IDisplayableEntity.hpp
  games/entity/IEntity.hpp
  games/types/KeyData.hpp
  games/types/SoundProps.hpp
  games/types/TextureProps.hpp
  graphics/IGraphicsFactory.hpp
  graphics/ISound.hpp
  graphics/ITexture.hpp
  graphics/events/IEvent.hpp
  graphics/events/key/AKeyEvent.hpp
  graphics/events/key/KeyPressEvent.hpp
  graphics/events/key/KeyReleaseEvent.hpp
  graphics/events/mouse/AMouseButtonEvent.hpp
  graphics/events/mouse/AMouseEvent.hpp
  graphics/events/mouse/MouseButtonPressEvent.hpp
  graphics/events/mouse/MouseButtonReleaseEvent.hpp
  graphics/events/mouse/MouseMoveEvent.hpp
  graphics/events/window/WindowCloseEvent.hpp
  graphics/events/window/WindowResizeEvent.hpp
  graphics/types/EntityProps.hpp
  graphics/window/IWindow.hpp
  graphics/window/IWindowIcon.hpp
  types/UUId.cpp
  types/UUId.hpp
  types/types.hpp
Labels: enhancement

#11 feat: add lib entrypoint exemple
  games/IEntity.hpp
  games/IGame.hpp
  games/IGameProvider.hpp
  games/components/ICollidableComponent.hpp
  games/components/IDisplayableComponent.hpp
  games/components/IKeyboardComponent.hpp
  games/components/IPositionComponent.hpp
  games/components/ISoundComponent.hpp
  games/export.cpp.example
  graphics/IGraphicsProvider.hpp
  graphics/export.cpp.example
  graphics/types/GraphicsManifest.hpp
  graphics/window/IWindow.hpp
  types/Libraries.hpp
  types/types.hpp
Labels: enhancement

#14 fix: bad call or return
  games/IGameProvider.hpp
  games/export.cpp.example
  graphics/IGraphicsProvider.hpp
  graphics/export.cpp.example
  types/Libraries.hpp
Labels: bug

#15 Fix IComponent entity getter and recursive include loop
  games/components/IComponent.hpp
  types/Libraries.hpp
  types/types.hpp
Labels: bug

#16 fix: remove useless window interface
  .gitignore
  graphics/IGraphicsProvider.hpp
  graphics/window/IWindowIcon.hpp
Labels: duplicate

#17 fix: remove bad call to unexistant interface
  games/IGame.hpp
  graphics/window/IWindow.hpp
Labels: bug

#20 feat(game): add properties to game
  games/IGame.hpp
  games/types/GameManifest.hpp
Labels: improvement

#21 fix(graphics): add missing ITexture namespace
  graphics/ITexture.hpp
Labels: bug

#22 fix(game): remove useless header
  games/types/GameManifest.hpp
Labels: bug

#24 Conformise shared part to project
  games/IEntity.hpp
  games/IGame.hpp
  games/components/IComponent.hpp
  graphics/IGraphicsProvider.hpp
  graphics/ISound.hpp
  graphics/IWindow.hpp
  graphics/events/IEvent.hpp
  graphics/events/IKeyEvent.hpp
  graphics/events/IMouseButtonEvent.hpp
  graphics/events/IMouseEvent.hpp
  graphics/events/key/AKeyEvent.hpp
  graphics/events/key/KeyPressEvent.hpp
  graphics/events/key/KeyReleaseEvent.hpp
  graphics/events/mouse/AMouseButtonEvent.hpp
  graphics/events/mouse/AMouseEvent.hpp
  graphics/events/mouse/MouseButtonPressEvent.hpp
  graphics/events/mouse/MouseButtonReleaseEvent.hpp
  graphics/events/mouse/MouseMoveEvent.hpp
  graphics/events/window/WindowCloseEvent.hpp
  graphics/events/window/WindowResizeEvent.hpp
  graphics/types/EntityProps.hpp
  types/UUId.cpp
  types/UUId.hpp
  types/types.hpp
Labels: improvement

#26 feat: add text component & update renderer methods
  games/components/IDisplayableComponent.hpp
  games/components/ITextComponent.hpp
  games/components/ITextureComponent.hpp
  graphics/IFont.hpp
  graphics/IGraphicsProvider.hpp
  graphics/IWindow.hpp
  graphics/types/EntityProps.hpp
  graphics/types/TextProps.hpp
  graphics/types/TextureProps.hpp
  types/Color.hpp
Labels: enhancement, improvement

#28 fix: color type syntax
  graphics/events/IEvent.hpp
  types/Color.hpp
Labels: bug

#29 refactor: entry points returned types and update Color
  games/export.cpp.example
  graphics/export.cpp.example
  types/Color.hpp
Labels: enhancement, improvement

#33 feat(graphics): add exceptions interfaces
  graphics/exceptions/IFontException.hpp
  graphics/exceptions/IGraphicsException.hpp
  graphics/exceptions/ISoundException.hpp
  graphics/exceptions/ITextureException.hpp
  graphics/exceptions/IWindowException.hpp
Labels: enhancement, improvement

#34 fix: update deltatime to native milli
  games/IGame.hpp
Labels: bug

#35 fix(graphics): missing include directive in exceptions
  graphics/exceptions/IGraphicsException.hpp
Labels: bug

#37 refactor(grpahics): exceptions extends now of std::exception
  graphics/exceptions/IGraphicsException.hpp
Labels: bug

#38 fix: enum conflicts between TextComponent and KeyboardComponent
  games/components/IKeyboardComponent.hpp
  games/components/ITextComponent.hpp
Labels: suggestion

#40 refactor(component): refactor position component to spatial component (add getSize)
  games/components/ICollidableComponent.hpp
  games/components/IComponent.hpp
  games/components/IDisplayableComponent.hpp
  games/components/IPositionableComponent.hpp
Labels: bug

#42 fix(component): fix component enum type
  games/components/IComponent.hpp
Labels: bug
