Repository G-Epitech/MAYBDF-ArcadeShared, pull requests merged in 2024-04, with the labels that each got.

#44 fix: remove useless reference of shared ptr for game events
  games/components/ICollidableComponent.hpp
  games/components/IDisplayableComponent.hpp
  games/components/IKeyboardComponent.hpp
  games/components/IPositionableComponent.hpp
  games/components/ISoundComponent.hpp
Labels: bug

#45 Change texture positions to floats
  games/IGame.hpp
  games/components/IPositionableComponent.hpp
  graphics/events/IMouseEvent.hpp
  graphics/types/TextProps.hpp
  graphics/types/TextureProps.hpp
Labels: enhancement

#46 Add documentation
  .gitignore
  Doxyfile
  README.md
  games/IEntity.hpp
  games/IGame.hpp
  games/IGameProvider.hpp
  games/components/ICollidableComponent.hpp
  games/components/IComponent.hpp
  games/components/IDisplayableComponent.hpp
  games/components/IKeyboardComponent.hpp
  games/components/IPositionableComponent.hpp
  games/components/ISoundComponent.hpp
  games/components/ITextComponent.hpp
  games/components/ITextureComponent.hpp
  games/types/GameManifest.hpp
  graphics/IFont.hpp
  graphics/IGraphicsProvider.hpp
  graphics/ISound.hpp
  graphics/ITexture.hpp
  graphics/IWindow.hpp
  graphics/events/IEvent.hpp
  graphics/events/IKeyEvent.hpp
  graphics/events/IMouseButtonEvent.hpp
  graphics/events/IMouseEvent.hpp
  graphics/exceptions/IFontException.hpp
  graphics/exceptions/IGraphicsException.hpp
  graphics/exceptions/ISoundException.hpp
  graphics/exceptions/ITextureException.hpp
  graphics/exceptions/IWindowException.hpp
  graphics/types/GraphicsManifest.hpp
  graphics/types/TextProps.hpp
  graphics/types/TextureProps.hpp
  types/Color.hpp
  types/Vector.hpp
Labels: documentation
